services:
  - type: web
    name: youtube-downloader-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: 7710160278:AAEuNEnQOfIz2zNMWGWLLNCiNwiBn_4h-gw
    plan: free
    env: python
    region: oregon
