services:
  - type: web
    name: yt-video-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BOT_TOKEN
        value: 8405906800:AAGWdrBtEyqTWVIP2nSTRHuWruJ7OrzAmek
      - key: WEBHOOK_URL
        value: https://yt-video-downloader.onrender.com